FROM microstrain/ros-microstrain_inertial_driver:ros

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV ROS_MASTER_URI="http://10.0.0.100:11311"
ENV ROS_IP="10.0.0.100"
ENV ROS_HOSTNAME="10.0.0.100"
SHELL ["/bin/bash", "-c"]
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
# CMD source /opt/ros/noetic/setup.bash  && roslaunch microstrain_inertial_driver microstrain.launch --wait; exit
